# Generated by Django 4.2.6 on 2024-04-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GradCam", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="user_images/")),
            ],
        ),
    ]
