# Generated by Django 4.2.6 on 2024-04-17 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GradCam", "0004_delete_image_userimage_upload_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
